name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Updated to match your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
        
      - name: Install dependencies
        run: |
          npm install
          npm install -D tailwindcss@3.3.5 postcss@8.4.31 autoprefixer@10.4.16 tailwindcss-animate
          echo "module.exports = {plugins: {tailwindcss: {},autoprefixer: {}}}" > postcss.config.js
          
      - name: Debug Environment
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Installed packages:"
          npm list --depth=0
          echo "Directory structure:"
          ls -la
        
      - name: Build
        run: |
          npm run build --verbose
          echo "Build completed, listing output files:"
          ls -la ./out || echo "No out directory found"
          
      - name: Prepare for GitHub Pages
        run: |
          # Create .nojekyll file
          touch ./out/.nojekyll
          
          # Debug information
          echo "Current directory structure before modifications:"
          ls -la ./out
          
          # Create index.html in root for redirection
          cat > ./out/index.html <<EOL
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Jairaj Kolhatkar Portfolio</title>
              <meta http-equiv="refresh" content="0; URL=/Portfolic">
              <link rel="canonical" href="https://jairajkolhatkar.github.io/Portfolic">
            </head>
            <body>
              <p>Redirecting to <a href="/Portfolic">portfolio</a>...</p>
            </body>
          </html>
          EOL
          
          # Create 404.html for GitHub Pages handling
          cp ./out/index.html ./out/404.html
          
          # Final directory check
          echo "Final directory structure:"
          ls -la ./out
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true  # This creates a clean gh-pages branch 