name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Updated to match your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          npm run build
          echo "Build completed, listing output files:"
          ls -la ./out
          
      - name: Prepare for GitHub Pages
        run: |
          # Create .nojekyll file
          touch ./out/.nojekyll
          
          # Debug information
          echo "Current directory structure before modifications:"
          ls -la ./out
          
          # Create index.html in root for redirection
          cat > ./out/index.html <<EOL
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Jairaj Kolhatkar Portfolio</title>
              <meta http-equiv="refresh" content="0; URL=/Portfolic">
              <link rel="canonical" href="https://jairajkolhatkar.github.io/Portfolic">
            </head>
            <body>
              <p>Redirecting to <a href="/Portfolic">portfolio</a>...</p>
            </body>
          </html>
          EOL
          
          # Create 404.html for GitHub Pages handling
          cp ./out/index.html ./out/404.html
          
          # Final directory check
          echo "Final directory structure:"
          ls -la ./out
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true  # This creates a clean gh-pages branch 